

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: backend_trello_db
      DB_USERNAME: root
      DB_PASSWORD: 

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: backend_trello_db
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
